--- A collection of types to be included / used in other Lua files.
---
--- These types are either required by the Lua API or required for the normal
--- operation of this Lua plugin.
---

---@alias treemotion.HintKind "word_boundaries" | "motions" | "none"

---@class treemotion.Configuration
---    The user's customizations for this plugin.
---@field commands treemotion.ConfigurationCommands?
---    Customize the fallback behavior of all `:TreeMotion` commands.
---@field hints treemotion.HintKind?
---    Which motion hints are currently visible. Only one kind may be active
---    at a time.
---@field logging treemotion.LoggingConfiguration?
---    Control how and which logs print to file / Neovim.

---@class treemotion.ResolvedConfiguration : treemotion.Configuration
---    `treemotion.Configuration` after the plugin's defaults have been merged
---    in (see `configuration._DEFAULTS`). Unlike `treemotion.Configuration`,
---    which may be a partial user override (e.g. `vim.g.treemotion_configuration`),
---    every field here is guaranteed to be present.
---@field logging treemotion.LoggingConfiguration
---    Control how and which logs print to file / Neovim. Always present,
---    though its own `use_console` / `use_file` fields may both be `false`.

---@class treemotion.ConfigurationCommands
---    Customize the fallback behavior of all `:TreeMotion` commands.
---@field goodnight_moon treemotion.ConfigurationGoodnightMoon?
---    The default values when a user calls `:TreeMotion goodnight-moon`.
---@field hello_world treemotion.ConfigurationHelloWorld?
---    The default values when a user calls `:TreeMotion hello-world`.
---@field motion treemotion.ConfigurationMotion?
---    Customize the `w`/`e`/`b`/`ge` sub-word splitting behavior.

---@class treemotion.ConfigurationMotion
---    Customize the `w`/`e`/`b`/`ge`/`W`/`E`/`B`/`gE` sub-word splitting behavior.
---@field small treemotion.ConfigurationMotionGroup?
---    Which naming conventions `w`/`e`/`b`/`ge` additionally split leaves on.
---@field big treemotion.ConfigurationMotionGroup?
---    Which naming conventions `W`/`E`/`B`/`gE` additionally split runs on.
---    Only takes effect once `enabled = true` -- by default `W`/`E`/`B`/`gE`
---    ignore case/delimiters entirely, the same way real Vim's `W` ignores
---    punctuation inside a WORD.
---@field comment_markers table<string, string[]>?
---    Which single characters count as comment-marker punctuation
---    (`comment_marker_case`'s target), keyed by treesitter language name
---    (`vim.treesitter.get_parser():lang()`, e.g. `"lua"`, `"c"`, `"vim"` --
---    not always the same as `'filetype'`; see `_comment_marker_characters`'s
---    docstring). Deliberately per-language rather than one fixed global set:
---    the same punctuation means different things in different grammars --
---    `"` opens a comment in Vimscript but closes a string everywhere else,
---    `;` ends a comment in a treesitter query file but ends a **statement** in
---    every C-family language -- so a character only gets `comment_marker_case`
---    treatment in the languages it's actually configured for here, never
---    globally. Unset entries fall back to `_DEFAULTS`' per-language list;
---    a language with no entry at all has no comment-marker characters, so
---    `comment_marker_case` is a no-op there until configured. `-`/`_` are no
---    exception to any of this -- despite also being `kebab_case`/`snake_case`'s
---    delimiters, a bare `-`/`_` run (a language's own comment opener, a
---    `-----` separator) only falls under `comment_marker_case` when the
---    language's own entry here lists that character; a language with no
---    `-`/`_` entry leaves a bare run of either under `kebab_case`/`snake_case`
---    instead, same as every other character (see `comment_marker_case`'s
---    docstring below). Beyond the languages shown here, roughly 120
---    additional languages are supported automatically, with no
---    configuration needed, as soon as their treesitter parser is installed
---    -- see `_OPTIONAL_COMMENT_MARKERS` in `configuration.lua` for the full
---    list and `configuration.get_comment_markers` for the resolution order.
---@field insignificant_characters table<string, string[]>?
---    Leaf-level tokens (e.g. `";"`, `"{"`, `"}"`, `"["`, `"]"`) that
---    `w`/`e`/`b`/`ge`/`W`/`E`/`B`/`gE` treat as entirely invisible, keyed by
---    treesitter language name -- same per-language-name convention as
---    `comment_markers`. A configured entry must match a leaf's **entire**
---    text exactly (not a substring it merely contains), so multi-character
---    tokens (`"->"`, `"::"`) work too, not just single characters. Only
---    applies to **code** leaves: a leaf tagged `@spell`/`@string` (prose, or
---    string content) never has any of its characters treated as
---    insignificant, since prose already does its own punctuation-is-a-word
---    splitting (`_split_prose_words`), deliberately mirroring how real Vim's
---    `w` treats punctuation as a landing stop in a text file -- the same
---    reason `.code`/`.prose` are configured separately everywhere else in
---    this type. The character itself is still real buffer text (`x`, `dd`,
---    highlighting, ... are all unaffected); only word-motion traversal
---    ignores it. Defaults to `{}` for every language -- unlike
---    `comment_markers`, this has no shipped or auto-detected defaults:
---    which punctuation counts as "insignificant" is a personal taste call,
---    not an objective fact about a grammar, so it's opt-in only.

---@class treemotion.ConfigurationMotionGroup
---    Sub-word splitting rules for one motion family (`small` = `w`/`e`/`b`/`ge`,
---    `big` = `W`/`E`/`B`/`gE`), configured separately for "code" leaves
---    (identifiers, ...) and "prose" leaves (comments, string content, or
---    any other span a treesitter query marks `@spell` or `@string` --
---    string content counts as prose too, since it just as often holds free
---    text -- a description, an error message, a URL -- as it does an
---    identifier-like slug; see `_is_prose_capture` in `subword.lua`).
---    Splitting a prose leaf/run first divides it into individual words (on
---    whitespace/punctuation, like real Vim's `w` in a text file) before
---    either ruleset ever runs; code leaves skip straight to these rules.
---@field enabled boolean?
---    `big` only (`small` never reads this field): whether `W`/`E`/`B`/`gE`
---    consult `code`/`prose`/`backtick_identifiers` at all. Defaults to
---    `false`, which is byte-for-byte today's behavior -- a run is always one
---    stop, ignoring case/delimiters entirely, the same way real Vim's `W`
---    ignores punctuation inside a WORD. Set to `true` to opt `W`/`E`/`B`/`gE`
---    into real case/delimiter-aware sub-splitting within each run.
---@field backtick_identifiers boolean?
---    Whether a backtick-enclosed span within prose that's exactly one Vim
---    word (`` `fooBar` ``, `` `foo-bar` `` -- not `` `foo bar` `` or an
---    empty `` `` ``) is treated as a code identifier: `code`'s
---    camel_case/pascal_case/kebab_case/snake_case/comment_marker_case rules
---    apply to it instead of `prose`'s, and the backticks themselves produce
---    no landing stop for `w`/`b`/`e`/`ge` -- invisible, the same way a
---    `"skip"` comment-marker run already is. A backtick pair whose content
---    isn't a single word is left as ordinary prose text, backticks
---    included -- no behavior change for it. Defaults to `true`.
---@field code treemotion.ConfigurationMotionSubwordRules?
---    Splitting rules for leaves that aren't tagged `@spell` or `@string`.
---@field prose treemotion.ConfigurationMotionSubwordRules?
---    Splitting rules for leaves (or, after the word split above, individual
---    words within a leaf) that are tagged `@spell` or `@string`.

---@alias treemotion.SubwordDelimiterMode "none" | "skip" | "stop"

---@class treemotion.ConfigurationMotionSubwordRules
---    Which naming conventions additionally split a leaf (or prose word) on.
---@field camel_case boolean?
---    Split lowercase-leading identifiers at case transitions, e.g. `fooBar` -> `foo`, `Bar`.
---@field pascal_case boolean?
---    Split uppercase-leading identifiers at case transitions, e.g. `FooBar` -> `Foo`, `Bar`.
---@field kebab_case treemotion.SubwordDelimiterMode?
---    How to handle `-` next to real identifier content, e.g. `foo-bar` ->
---    `foo`, `bar` (`"skip"`) or `foo`, `-`, `bar` (`"stop"`). Only applies
---    when `-` sits beside a letter/digit; a run that's **only** `-` (a
---    language's own comment opener, a `-----` separator) is a bare
---    punctuation marker instead, so `comment_marker_case` governs it **if**
---    the current language's `comment_markers` lists `-` -- otherwise this
---    setting keeps governing even a bare run, since there's nothing else
---    configured to hand it off to. See `comment_marker_case`.
---@field snake_case treemotion.SubwordDelimiterMode?
---    How to handle `_` next to real identifier content, e.g. `foo_bar` ->
---    `foo`, `bar` (`"skip"`) or `foo`, `_`, `bar` (`"stop"`). Same
---    real-identifier-content caveat as `kebab_case`: a run that's only `_`
---    falls to `comment_marker_case` only if the current language's
---    `comment_markers` lists `_`; no language does by default.
---@field comment_marker_case treemotion.SubwordDelimiterMode?
---    How to handle a run of the current language's comment-marker
---    punctuation (see `comment_markers`), e.g. `/// text` -> `text`
---    (`"skip"`, jumps straight past a Rust-style `///` marker) or `///`,
---    `text` (`"stop"`, the marker is its own stop first). Also governs a
---    bare `-`/`_` run with no identifier content beside it (Lua's `--`
---    comment opener, a `-----` separator, a `///` doc-comment marker) --
---    but, like every other marker character, only in languages whose
---    `comment_markers` entry actually lists `-`/`_`; `kebab_case`/`snake_case`
---    keep governing a bare run in every other language, the same as they
---    already do next to real identifier content. This one setting still
---    applies uniformly across languages; only *which characters* count as a
---    marker in the first place is per-language, via `comment_markers`.
---@field colon_case treemotion.SubwordDelimiterMode?
---    How to handle `:` next to real identifier content, same semantics as
---    `kebab_case`/`snake_case`. Exists so structured tokens that use `:` as
---    a separator -- a `github:owner/repo` reference, a URL's `https:` --
---    don't force a landing stop on it. Defaults to `"skip"` for `prose`
---    (ignored, so those references read as intended) and `"none"` for
---    `code` (real identifiers essentially never contain a literal `:`, so
---    this is inert there by default).
---@field slash_case treemotion.SubwordDelimiterMode?
---    How to handle `/` next to real identifier content, same semantics as
---    `kebab_case`/`snake_case`. Exists for the same reason as `colon_case`
---    -- URLs (`https://host/path`) and filesystem paths (`/a/b/c`,
---    `./a/b/c`) use `/` as a separator, not a landing stop. Same defaults as
---    `colon_case`: `"skip"` for `prose`, `"none"` for `code`.
---@field opaque_token_min_length integer?
---    Minimum length (after stripping trailing `=` padding) for a run to be
---    tested against the hash/digest heuristic: it counts as opaque -- one
---    unit, never case- or delimiter-split internally -- if it's at least
---    this long and either entirely hex digits, or drawn from the base64
---    alphabet (`%w`, `+`, `/`) with an uppercase letter, a lowercase
---    letter, and a digit all somewhere in it. This is a pure heuristic
---    (charset + length), not a list of known algorithms, so it also
---    matches things that merely look hash-shaped. Defaults to `20` --
---    comfortably under a 40-character sha1 hex digest or a 44-character
---    base64 sha256 digest, comfortably over an ordinary identifier or word.

---@class treemotion.ConfigurationGoodnightMoon
---    The default values when a user calls `:TreeMotion goodnight-moon`.
---@field read treemotion.ConfigurationGoodnightMoonRead?
---    The default values when a user calls `:TreeMotion goodnight-moon read`.

---@class treemotion.LoggingConfiguration
---    Control whether or not logging is printed to the console or to disk.
---@field level ("trace" | "debug" | "info" | "warning" | "error" | "fatal")?
---    Any messages above this level will be logged. Only these string values
---    are accepted -- unlike Neovim's own `vim.log.levels.*`, `mega.logging`
---    (which this field is passed into) does not handle numeric levels
---    correctly, so they are intentionally not part of this type.
---@field use_console boolean?
---    Should print the output to neovim while running. Warning: This is very
---    spammy. You probably don't want to enable this unless you have to.
---@field use_file boolean?
---    Should write to a file.
---@field output_path string?
---    The default path on-disk where log files will be written to.
---    Defaults to "/home/selecaoone/.local/share/nvim/plugin_name.log".

---@class treemotion.ConfigurationGoodnightMoonRead
---    The default values when a user calls `:TreeMotion goodnight-moon read`.
---@field phrase string
---    The book to read if no book is given by the user.

---@class treemotion.ConfigurationHelloWorld
---    The default values when a user calls `:TreeMotion hello-world`.
---@field say treemotion.ConfigurationHelloWorldSay?
---    The default values when a user calls `:TreeMotion hello-world say`.

---@class treemotion.ConfigurationHelloWorldSay
---    The default values when a user calls `:TreeMotion hello-world say`.
---@field repeat number
---    A 1-or-more value. When 1, the phrase is said once. When 2+, the phrase
---    is repeated that many times.
---@field style "lowercase" | "uppercase"
---    Control how the text is displayed. e.g. "uppercase" changes "hello" to "HELLO".
