--- A collection of types to be included / used in other Lua files.
---
--- These types are either required by the Lua API or required for the normal
--- operation of this Lua plugin.
---

---@class treemotion.Configuration
---    The user's customizations for this plugin.
---@field commands treemotion.ConfigurationCommands?
---    Customize the fallback behavior of all `:TreeMotion` commands.
---@field hints treemotion.HintKind?
---    Which motion hints are currently visible. Only one kind may be active
---    at a time.
---@field logging treemotion.LoggingConfiguration?
---    Control how and which logs print to file / Neovim.

---@class treemotion.ResolvedConfiguration : treemotion.Configuration
---    `treemotion.Configuration` after the plugin's defaults have been merged
---    in (see `configuration._DEFAULTS`). Unlike `treemotion.Configuration`,
---    which may be a partial user override (e.g. `vim.g.treemotion_configuration`),
---    every field here is guaranteed to be present.
---@field logging treemotion.LoggingConfiguration
---    Control how and which logs print to file / Neovim. Always present,
---    though its own `use_console` / `use_file` fields may both be `false`.

---@alias treemotion.HintKind "word_boundaries" | "motions" | "none"

---@class treemotion.ConfigurationCommands
---    Customize the fallback behavior of all `:TreeMotion` commands.
---@field goodnight_moon treemotion.ConfigurationGoodnightMoon?
---    The default values when a user calls `:TreeMotion goodnight-moon`.
---@field hello_world treemotion.ConfigurationHelloWorld?
---    The default values when a user calls `:TreeMotion hello-world`.
---@field motion treemotion.ConfigurationMotion?
---    Customize the `w`/`e`/`b`/`ge` sub-word splitting behavior.

---@class treemotion.ConfigurationMotion
---    Customize the `w`/`e`/`b`/`ge` sub-word splitting behavior.
---@field subword treemotion.ConfigurationMotionSubword?
---    Which naming conventions `w`/`e`/`b`/`ge` additionally split leaves on.
---    `W`/`E`/`B`/`gE` are unaffected -- they ignore case entirely, the same
---    way real Vim's `W` ignores punctuation.

---@class treemotion.ConfigurationMotionSubword
---    Sub-word splitting rules, configured separately for "code" leaves
---    (identifiers, string content, ...) and "prose" leaves (comments, or
---    any other span a treesitter `@spell` query marks as natural-language
---    text). Splitting a prose leaf first divides it into individual words
---    (on whitespace/punctuation, like real Vim's `w` in a text file) before
---    either ruleset ever runs; code leaves skip straight to these rules.
---@field comment_markers table<string, string[]>?
---    Which single characters count as comment-marker punctuation
---    (`comment_marker_case`'s target), keyed by treesitter language name
---    (`vim.treesitter.get_parser():lang()`, e.g. `"lua"`, `"c"`, `"vim"` --
---    not always the same as `'filetype'`; see `_comment_marker_characters`'s
---    docstring). Deliberately per-language rather than one fixed global set:
---    the same punctuation means different things in different grammars --
---    `"` opens a comment in Vimscript but closes a string everywhere else,
---    `;` ends a comment in a treesitter query file but ends a *statement* in
---    every C-family language -- so a character only gets `comment_marker_case`
---    treatment in the languages it's actually configured for here, never
---    globally. Unset entries fall back to `_DEFAULTS`' per-language list;
---    a language with no entry at all has no comment-marker characters, so
---    `comment_marker_case` is a no-op there until configured. `-`/`_` are
---    never part of this list -- a bare `-`/`_` run (Lua's `--`, a `-----`
---    separator) already falls to `comment_marker_case` unconditionally,
---    language-agnostically, via `kebab_case`/`snake_case`'s own bare-run
---    rule (see `comment_marker_case`'s docstring below).
---@field code treemotion.ConfigurationMotionSubwordRules?
---    Splitting rules for leaves that aren't tagged `@spell`.
---@field prose treemotion.ConfigurationMotionSubwordRules?
---    Splitting rules for leaves (or, after the word split above, individual
---    words within a leaf) that are tagged `@spell`.

---@alias treemotion.SubwordDelimiterMode "none" | "skip" | "stop"
---    How `kebab_case`/`snake_case` treat a `-`/`_` delimiter once found:
---    `"none"` leaves it embedded, not a split point at all; `"skip"` splits
---    on it but drops the delimiter character itself, so no unit ever lands
---    on it; `"stop"` splits on it *and* keeps the delimiter as its own unit.

---@class treemotion.ConfigurationMotionSubwordRules
---    Which naming conventions additionally split a leaf (or prose word) on.
---@field camel_case boolean?
---    Split lowercase-leading identifiers at case transitions, e.g. `fooBar` -> `foo`, `Bar`.
---@field pascal_case boolean?
---    Split uppercase-leading identifiers at case transitions, e.g. `FooBar` -> `Foo`, `Bar`.
---@field kebab_case treemotion.SubwordDelimiterMode?
---    How to handle `-` next to real identifier content, e.g. `foo-bar` ->
---    `foo`, `bar` (`"skip"`) or `foo`, `-`, `bar` (`"stop"`). Only applies
---    when `-` sits beside a letter/digit; a run that's *only* `-` (Lua's
---    `--`, a `-----` separator) is a bare punctuation marker instead, so
---    `comment_marker_case` governs it -- see that field.
---@field snake_case treemotion.SubwordDelimiterMode?
---    How to handle `_` next to real identifier content, e.g. `foo_bar` ->
---    `foo`, `bar` (`"skip"`) or `foo`, `_`, `bar` (`"stop"`). Same
---    real-identifier-content caveat as `kebab_case`: a run that's only `_`
---    falls to `comment_marker_case` instead.
---@field comment_marker_case treemotion.SubwordDelimiterMode?
---    How to handle a run of the current language's comment-marker
---    punctuation (see `comment_markers`), e.g. `/// text` -> `text`
---    (`"skip"`, jumps straight past a Rust-style `///` marker) or `///`,
---    `text` (`"stop"`, the marker is its own stop first). Also governs
---    `-`/`_` whenever the whole run has no identifier content beside it
---    (Lua's `--` comment opener, a `-----` separator, a `///` doc-comment
---    marker) -- `kebab_case`/`snake_case` only take over once `-`/`_` sits
---    next to a real letter/digit, like `hello-world`. This one setting
---    still applies uniformly across languages; only *which characters*
---    count as a marker in the first place is per-language, via `comment_markers`.

---@class treemotion.ConfigurationGoodnightMoon
---    The default values when a user calls `:TreeMotion goodnight-moon`.
---@field read treemotion.ConfigurationGoodnightMoonRead?
---    The default values when a user calls `:TreeMotion goodnight-moon read`.

---@class treemotion.LoggingConfiguration
---    Control whether or not logging is printed to the console or to disk.
---@field level ("trace" | "debug" | "info" | "warning" | "error" | "fatal")?
---    Any messages above this level will be logged. Only these string values
---    are accepted -- unlike Neovim's own `vim.log.levels.*`, `mega.logging`
---    (which this field is passed into) does not handle numeric levels
---    correctly, so they are intentionally not part of this type.
---@field use_console boolean?
---    Should print the output to neovim while running. Warning: This is very
---    spammy. You probably don't want to enable this unless you have to.
---@field use_file boolean?
---    Should write to a file.
---@field output_path string?
---    The default path on-disk where log files will be written to.
---    Defaults to "/home/selecaoone/.local/share/nvim/plugin_name.log".

---@class treemotion.ConfigurationGoodnightMoonRead
---    The default values when a user calls `:TreeMotion goodnight-moon read`.
---@field phrase string
---    The book to read if no book is given by the user.

---@class treemotion.ConfigurationHelloWorld
---    The default values when a user calls `:TreeMotion hello-world`.
---@field say treemotion.ConfigurationHelloWorldSay?
---    The default values when a user calls `:TreeMotion hello-world say`.

---@class treemotion.ConfigurationHelloWorldSay
---    The default values when a user calls `:TreeMotion hello-world say`.
---@field repeat number
---    A 1-or-more value. When 1, the phrase is said once. When 2+, the phrase
---    is repeated that many times.
---@field style "lowercase" | "uppercase"
---    Control how the text is displayed. e.g. "uppercase" changes "hello" to "HELLO".
