name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'lua/**'
      - 'markdown/**'
      - 'README.md'
      - '.github/workflows/documentation.yml'

jobs:
  check_documentation_branch:
    name: Check For A Documentation Branch
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check_branch.outputs.exists }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check If A Valid Documentation Branch Exists
        id: check_branch
        run: |
          if git ls-remote --exit-code origin refs/heads/gh-pages; then
            echo "The branch exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "The branch does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  html_documentation:
    needs: check_documentation_branch
    if: needs.check_documentation_branch.outputs.exists == 'true'
    name: HTML Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install emmylua_doc_cli From crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: emmylua_doc_cli

      - name: Generate Mkdocs Files With emmylua_doc_cli
        run: emmylua_doc_cli --input lua/ --output markdown/generated --mixin markdown/manual

      - name: Deploy To GitHub Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: markdown/generated/mkdocs.yml


  vim_documentation:
    name: Vim Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Cache Nix Store
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Create API Documentation
        run: nix run .#api-documentation

      - name: Create User Documentation
        run: nix run .#user-documentation

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs(vimdoc): Auto-generate user / API documentation + vimtags"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
